### ISSUE TITLE
volume differences in different timeframes

### ISSUE THREAD

**Issue by Flippo24** [swimclan/gdax-candles#4]
I tried the same product in two different timeframes. 1m and 2m. The volume in the 2m candle should be addition of the both 1m candles, or i am wrong? But this is different. Ohlc seams right to me.

```
const Chart = require('./src/Chart');

const product = 'ETH-USD';
const timeframe = '1m';
const timeframe2 = '2m';
const ethereumChart1 = new Chart( product, timeframe ).start();
const ethereumChart2 = new Chart( product, timeframe2 ).start();

ethereumChart1.on('close', candle => {
  console.log('timeframe 1m');
  console.log(candle);
});

ethereumChart2.on('close', candle => {
  console.log('timeframe 2m');
  console.log(candle);
});
```

output:

```
timeframe 1m
Candlestick {
  timestamp: 2018-07-04T20:42:52.620Z,
  product: 'ETH-USD',
  open: 473.72,
  price: 473.72,
  close: 473.72,
  high: 473.72,
  low: 473.72,
  closed: true,
  height: 0,
  spread: 0,
  volume: 15.489755259999999,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
timeframe 2m
Candlestick {
  timestamp: 2018-07-04T20:43:49.910Z,
  product: 'ETH-USD',
  open: 473.72,
  price: 473.72,
  close: 473.72,
  high: 473.72,
  low: 473.71,
  closed: true,
  height: 0,
  spread: 0.00002110951616999018,
  volume: 13.47577175,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
timeframe 1m
Candlestick {
  timestamp: 2018-07-04T20:43:49.910Z,
  product: 'ETH-USD',
  open: 473.72,
  price: 473.72,
  close: 473.72,
  high: 473.72,
  low: 473.71,
  closed: true,
  height: 0,
  spread: 0.00002110951616999018,
  volume: 5.78294257,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
```

For me only the github source is working and i have to remove the bracket in Chart constructor. If i leave them, then always 'BTC-USD' and 1s timeframe will be used.

**Comment by swimclan** [comment]
@Flippo24 I am wondering if the `1m` candles that you are looking at aren't culminating into the `2m` that you are looking at.  When I did this I see generally good results (8.5 + 5.3 = 13.8):

```
----------- 1m -----------
 Candlestick {
  timestamp: 2018-07-04T23:40:43.363Z,
  product: 'ETH-USD',
  open: 465.74,
  price: 465.02,
  close: 465.02,
  high: 465.74,
  low: 465.02,
  closed: true,
  height: 0.001548320502344044,
  spread: 0.001548320502344044,
  volume: 8.509116359999998,
  sma: {},
  ema: {},
  color: 'red',
  regression: {} }
----------- 2m -----------
 Candlestick {
  timestamp: 2018-07-04T23:41:49.700Z,
  product: 'ETH-USD',
  open: 465.74,
  price: 465.11,
  close: 465.11,
  high: 465.74,
  low: 465.02,
  closed: true,
  height: 0.001354518285996851,
  spread: 0.0015480208982821854,
  volume: 13.819420039999999,
  sma: {},
  ema: {},
  color: 'red',
  regression: {} }
----------- 1m -----------
 Candlestick {
  timestamp: 2018-07-04T23:41:49.700Z,
  product: 'ETH-USD',
  open: 465.02,
  price: 465.11,
  close: 465.11,
  high: 465.11,
  low: 465.02,
  closed: true,
  height: 0.0001935026122853343,
  spread: 0.0001935026122853343,
  volume: 5.33552924,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
```

As far as the github source only working for you, can you explain a bit deeper what is going on?  Are you able to install the npm module into your node.js project?  Also what version of Node are you running?  I am running v9.4.0 and not having any issues.  

Here is the source of the code that executed above:

```
const Chart = require('gdax-candles');

const ethChartOneMinute = new Chart({ product: 'ETH-USD', timeframe: '1m' }).start();
const ethChartTwoMinute = new Chart({ product: 'ETH-USD', timeframe: '2m' }).start();

ethChartOneMinute.on('close', candle => console.log('----------- 1m -----------\n', candle));
ethChartTwoMinute.on('close', candle => console.log('----------- 2m -----------\n', candle));

```

**Comment by Flippo24** [comment]
I am runing v8.9.4.

I create a new project, installed gdax-candles from npm and used your code.
Your code is running, but i have also differences and correct volumes like yours.

Have a look at 8:36 and 8:37.
Sorry for scrolling.

```
----------- 1m -----------
 Candlestick {
  timestamp: 2018-07-05T08:35:56.865Z,
  product: 'ETH-USD',
  open: 470.22,
  price: 470.23,
  close: 470.23,
  high: 470.23,
  low: 470.22,
  closed: true,
  height: 0.000021266188886270346,
  spread: 0.000021266188886270346,
  volume: 7.62722574,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
----------- 1m -----------
 Candlestick {
  timestamp: 2018-07-05T08:36:42.834Z,
  product: 'ETH-USD',
  open: 470.23,
  price: 470.23,
  close: 470.23,
  high: 470.23,
  low: 470.23,
  closed: true,
  height: 0,
  spread: 0,
  volume: 5.75319543,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
----------- 2m -----------
 Candlestick {
  timestamp: 2018-07-05T08:37:51.050Z,
  product: 'ETH-USD',
  open: 470.23,
  price: 470.22,
  close: 470.22,
  high: 470.23,
  low: 470.22,
  closed: true,
  height: 0.000021266641146677947,
  spread: 0.000021266641146677947,
  volume: 10.57223761,
  sma: {},
  ema: {},
  color: 'red',
  regression: {} }
----------- 1m -----------
 Candlestick {
  timestamp: 2018-07-05T08:37:51.050Z,
  product: 'ETH-USD',
  open: 470.23,
  price: 470.22,
  close: 470.22,
  high: 470.23,
  low: 470.22,
  closed: true,
  height: 0.000021266641146677947,
  spread: 0.000021266641146677947,
  volume: 3.3442667299999997,
  sma: {},
  ema: {},
  color: 'red',
  regression: {} }
----------- 1m -----------
 Candlestick {
  timestamp: 2018-07-05T08:38:00.005Z,
  product: 'ETH-USD',
  open: 470.22,
  price: 470.22,
  close: 470.22,
  high: 470.22,
  low: 470.22,
  closed: true,
  height: 0,
  spread: 0,
  volume: 0,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
----------- 2m -----------
 Candlestick {
  timestamp: 2018-07-05T08:39:57.235Z,
  product: 'ETH-USD',
  open: 470.22,
  price: 470.23,
  close: 470.23,
  high: 470.23,
  low: 470.22,
  closed: true,
  height: 0.000021266188886270346,
  spread: 0.000021266188886270346,
  volume: 1.28201739,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
----------- 1m -----------
 Candlestick {
  timestamp: 2018-07-05T08:39:57.235Z,
  product: 'ETH-USD',
  open: 470.22,
  price: 470.23,
  close: 470.23,
  high: 470.23,
  low: 470.22,
  closed: true,
  height: 0.000021266188886270346,
  spread: 0.000021266188886270346,
  volume: 1.28201739,
  sma: {},
  ema: {},
  color: 'green',
  regression: {} }
``` 

When i use the npm module i cant use the variables for product and timeframe, like you discripe in the example. Then i only get the 2m candle every second. 

```
const Chart = require('gdax-candles');
const product = 'ETH-USD';
const timeframe = '1m';
const timeframe2 = '2m';
const ethereumChart1 = new Chart({ product, timeframe} ).start();
const ethereumChart2 = new Chart({ product, timeframe2} ).start();
```

Sorry, am new to node and js world.

**Comment by swimclan** [comment]
I am thinking that maybe node 8 doesn’t support object destructuring?  Try upgrading to node 9.x

On the volume thing, I see what you are saying.  Something it going on where one candle might be getting a socket event that the other is not hence the volumes being different.  I can think about another approach rather than simply incrementing volume on each socket update...

EDIT --  Looks like Node 8 does support object destructuring.  So its something else

**Comment by Flippo24** [comment]
I updated to v10.6.0 today and no difference to v8.9.4.

**Comment by Flippo24** [comment]
I have some ideas.

1) Why not change to always get 1s candles and add them together to the requested timeframe. So if a 1m candle is requested, then the 60 x 1s candles are calculated together. 1h = 3600x 1s candles. And so on. 
This would reduce bandwidth cause ther will be no other websocket connections for the same product to gdax. And you wont need an other 'clock' which needs cpu time.

edit: There is no need to create an array with 3600 candles. *lol* just update the 1h candle when the 1s candle closes. 

2) There can also be an event to get the actual candle even if it is not closed. So you have a live candle, which is calculated every second (or with every data, time independent). It could also be an parameter, to update the last candle in the array, before closing.

This may be wont fix the problem, but it could be an workaround with some improvements. Just think about it and let me know.

**Comment by swimclan** [comment]
@Flippo24 I havent forgotten about you!  I am looking into this today..  I like both these ideas but they may require significant rework of the module.  BUT, your idea about multiple clocks definitely triggered an idea.  I think that no matter how many instances of `Chart` the user creates, there should only be ONE clock.  This way they are all synced up to the exact same open and close event triggering.  I think I could use a single `Clock` instance across all instances of `Chart` and this may get better....

Let me try that first.  If that doesnt help, then maybe I can look at rewiring this to collect 1s candles like you said.  That is a nice idea.

Thanks again for your input on testing this library, it could go a long way towards keeping the project alive!

**Comment by swimclan** [comment]
@Flippo24 this should be fixed (or at least dramatically better).  Here is an example where I log out the volumes across a 10s and a 20s chart for BTC-USD:

Code:

```js
const Chart = require('gdax-candles');

const btcChartOne = new Chart({ product: 'BTC-USD', timeframe: '10s' }).start();
const btcChartTwo = new Chart({ product: 'BTC-USD', timeframe: '20s' }).start();


btcChartOne.on('close', candle => {
  console.log('----------10s----------');
  console.log(candle.volume);
});
btcChartTwo.on('close', candle => {
  console.log('----------20s----------');
  console.log(candle.volume);
});
```

Logged output:
```shell
----------10s----------
0.14633452
----------10s----------
0.04972552
----------20s----------
0.19606004               <----- equals 0.14633452 + 0.04972552
----------10s----------
0.19472379
----------10s----------
0.01944017
----------20s----------
0.21416396000000001 .  <------ equals 0.19472379 + 0.01944017
----------10s----------
0.34446909000000003
----------10s----------
0.49364123000000004
----------20s----------
0.91665023                  <----- slightly off but very close
----------10s----------
0.3025603
----------10s----------
0.25449897
----------20s----------
0.55705927
----------10s----------
0.4125304799999999
----------10s----------
0.49024831
----------20s----------
0.9027787899999998
----------10s----------
0.50960845
----------10s----------
0.03347349
----------20s----------
0.54308194
```

**Comment by swimclan** [comment]
@Flippo24 I updated the volume calculation again (v1.5.2) where I am using the 'match' message on the socket feed.  I tested this and now all the volumes are the same as the charts on Coinbase!  And they add up across different time resolutions.  So now I feel very confident that the numbers are real.  Please go ahead and test the library (via NPM) at v1.5.2 and let me know what you see.

Again, thank you so much for doing this testing and making some great suggestions.

~swimclan

**Comment by Flippo24** [comment]
Now it's working very well with different products and timeframes. Thanks a lot.
