### ISSUE TITLE
Why is the code so bloated?

### ISSUE THREAD

**Issue by slidenerd** [swimclan/gdax-candles#9]
I am sorry if this is a silly question. I went through your code and saw that you have a clock class with a setInterval that runs every 1 millisecond (very heavy on the CPU) and a websocket that opens one connection per pair (not a great idea) and a price class that is an event emitter coupled with rxjs on top of everything, why have you overcomplicated everything. The code below generates the same candles without running setInterval or rxjs fancy stuff. You can have an EventEmitter emit a candle and clear the old candle from the candles object below.

- Is this something you tried before and had some issues because of which you went the complex route? 

- Another serious issue is inside your clock class in the setInterval, you are calling tick method every millisecond, I benchmarked and some of its runs take 1 millisecond, this is not good as the operations will add up if the duration of the tick s execution were to go beyond a millisecond

- Also it doesnt look like you are using the timestamp of the incoming matches to set their date, your date will always be off by a small margin because of the lag between the actual event and the time you get the event

I would like to hear your opinions on this

```

"use strict";
const WebSocket = require('ws');

let ws = new WebSocket('wss://ws-feed.pro.coinbase.com')

ws.on('open', () => {

  ws.send(JSON.stringify({
    "type": "subscribe",
    "product_ids": [
      "ETH-USD"
    ],
    "channels": [
      "matches"
    ]
  }))
})

let candles = {}

ws.on('message', msg => {
  msg = JSON.parse(msg);
  if (!msg.price)
    return;

  if (!msg.size)
    return;

  msg.price = parseFloat(msg.price)
  msg.size = parseFloat(msg.size)
  let roundedTime = Math.floor(new Date(msg.time).getTime()/60000) * 60

  if(!candles[roundedTime]){

    let keys = Object.keys(candles).sort()
    console.log(candles[keys[keys.length - 1]])

    candles[roundedTime] = {
      time: roundedTime,
      open: msg.price,
      high: msg.price,
      low: msg.price,
      close: msg.price,
      volume: msg.size
    }
  }
  else{
    let candle = candles[roundedTime]
    candle.high = msg.price > candle.high ? msg.price : candle.high
    candle.low = msg.price < candle.low ? msg.price : candle.low
    candle.close = msg.price
    candle.volume += msg.size
  }

  

  setTimeout(() => {
    ws.terminate()
  }, 1200000)
})



```

Take a look at what happens here sometimes
```
  tick() {
    let start = Date.now().valueOf()
    let emit = false;
    this.now = Date.now().valueOf();
    for (var resolution in this.nextTimes) {
      if (this.now >= this.nextTimes[resolution]) {
        this.currentTicks.push(resolution);
        emit = true;
      }
    }
    emit && this.emit('tick', this.currentTicks);
    this.getNextTimes();
    this.currentTicks = [];
    console.log('ticking',Date.now().valueOf() - start);
  }
```

**Comment by Flippo24** [comment]
@slidenerd I don't understand the hole clock part. But this works an other way then your example. When your interval is 60000 and no new message arrived for 5 mins, then you wont get candles for the time between. In gdax-candles you will and they are very acorate. Thats why the time is checked every ms, so in the moment (or ca. 1 ms later) your computers time change minutes the minute-candle will be served. I havent found others projects like this. Have you tried it?

**Comment by swimclan** [comment]
@slidenerd thanks for your comments.  I agree that there is probably some bloat here but your example doesn’t accomplish what this module sets out to achieve.  I don’t want to create an arbitrary candlestick based only on when the price changes.  The clock is supposed to run completely independently of the market changes.  That’s how a chart works.

The 1ms resolution is actually too slow.  I would want to make the resolution at the microsecond level of granularity if I could but JS is too slow.  Plus the tick function back pressure should be easily managed by JS macro queue.  I have run this module on a basic cheap digital ocean droplet and have seen good performance so I don’t think cpu drain is a problem.

Thanks again for your interest in the module!

**Comment by slidenerd** [comment]
Interesting...I never considered that possibility given how liquid GDAX was with all the pairs but I can totally see this problem for a not-so popular pair on maybe some other exchange. Since you mentioned that you want to be able to run this in microseconds if possible, one thing you can try is to do a setInterval 0 which would run infinitely as fast as possible without causing a stackoverflow, however in that case, I think an instance of clock should be global to ensure we dont have multiple timers running infinitely and perhaps it can emit an event to which the chart class responds to...I ll try to work this out and come up with a better solution if possible, thanks for your insight

**Comment by swimclan** [comment]
@slidenerd great points about the clock singleton.  And actually @Flippo24 had also suggested this over the summer and we implemented it on clock.js.  You will notice that there is a module-scoped instance that is exported via the `getInstance()` method which should ensure a single shared instance for each implementation of chart.  With this in place you can be sure that two listeners that are listening to different time intervals of the same currency pair will be doing so against the same clock.  It was a pretty neat little update.  

If you ever want to contribute to the project I would be happy to work with you.  @Flippo24 made some invaluable suggestions and really helped make the library even better.

**Comment by slidenerd** [comment]
```
const EventEmitter = require('events');

const units = {
    s: 1,
    m: 60,
    h: 3600,
    d: 86400
}

let timeframeToSec = (timeframe) => {

    let time = '';
    let unit;
    const tfsplit = timeframe.split('');
    for (var i in tfsplit) {
        if (!isNaN(tfsplit[i])) {
            time += tfsplit[i];
        } else {
            unit = tfsplit[i];
            break;
        }
    }
    return unit && units[unit] && time.length > 0 ? Number(time) * units[unit] : units.s;
}

let timeLeft = (epoch, interval) => {
    return interval - (Math.floor(Number(epoch) / 1000) % interval);
}

let nextTime = (epoch, interval) => {
    return (Math.floor(epoch / 1000) + timeLeft(epoch, interval)) * 1000;
}

class Clock extends EventEmitter {
    constructor(resolution = '1s') {
        super();
        this.started = false;
        this.resolution = timeframeToSec(resolution);
        this.resolutions = [];
        this.nextTimes = {};
        this.currentTicks = [];
        this.runs = 0;
    }

    start() {
        if (!this.started) {
            this.now = Date.now().valueOf();
            this.getNextTimes();
            setTimeout(this.tick.bind(this), 0);
            this.started = true;
        }
        return this;
    }

    tick() {
        this.runs++;
        let emit = false;
        this.now = Date.now().valueOf();
        for (var resolution in this.nextTimes) {
            if (this.now >= this.nextTimes[resolution]) {
                this.currentTicks.push(resolution);
                emit = true;

            }
        }
        emit && this.emit('tick', this.currentTicks, this.runs);
        if (emit)
            this.runs = 0;
        this.getNextTimes();
        this.currentTicks = [];
        setTimeout(this.tick.bind(this), 0);
    }

    getNextTimes() {
        for (let i = 0, len = this.resolutions.length; i < len; i++) {
            let resolution = this.resolutions[i];
            this.nextTimes[resolution] = nextTime(this.now, timeframeToSec(resolution));
        }
        return this.nextTimes;
    }

    addResolution(resolution) {
        this.resolutions.indexOf(resolution) === -1 && (this.resolutions.push(resolution));
    }
}

let instance
let getInstance = function (resolution = '1s') {
    if (!instance) {
        instance = new Clock(resolution);
    }
    instance.addResolution(resolution);
    return instance;
}

let c = getInstance('1m').start()
c.on('tick', (ticks, runs) => console.log(ticks, Date.now().valueOf(), runs))
```

Not much difference but I modified the code slightly to run a setTimeout at 0 instead of a setInterval and replace a forEach with a native for, 

- I feel recursive setTimeout would prevent a possible queue explosion that may be caused by setInterval where one run takes more than 1ms as described here in the recursive setTimeout section. Would love to hear your thoughts on it
https://javascript.info/settimeout-setinterval

- This is also something to consider https://stackoverflow.com/questions/18880593/run-a-function-for-each-milliseconds

- Also, have you come across this by any chance https://www.npmjs.com/package/nanotimer

- Also for is much faster than a forEach, normally I wont even bother about such things but given we want to run this loop literally every millisecond , I think it makes a difference

**Comment by swimclan** [comment]
@slidenerd this appears to be a nice improvement and I appreciate all your comments.  Can you get this onto a branch and PR this so I can play with it?

**Comment by Flippo24** [comment]
nanotimer or process.hrtime is a good approach. But i think the timer resolution is not a problem. There is a big time difference in message.time and system clock. I've checked it yesterday and found an difference of ~440ms. So candles could have the wrong data.
To solve this, an avereage of this difference should be added to the timer. I dont like the idea to change the system clock for every exchange i use.

**Comment by slidenerd** [comment]
@Flippo24 while I havent exactly tested nanotimer, what is the highest frequency at which you are getting messages from an exchange, if I am not mistaken I read somewhere on stackoverflow than the websocket sends a max 50 messages per second translating to a 20ms frequency. If this really is true, we can check every 10 ms with a setInterval then just to set things in motion at 2x, the CPU hammering will go down significantly, @swimclan sure, gimme a day or two and do a PR, mid-week gets hectic :)

**Comment by Flippo24** [comment]
@slidenerd it depends on market situations how much messages you will get from the exchange. This isn't fix. Some exchanges won't give tick data, but every second, when something changed. Never heard of this websocket limitation. Maybe there is one, depending on your OS.

On this example with 4 pairs in 2 different timeframes my cpu (i7-4770k) works very hard with 0-0.7% avg may be 0.2%. There is definitly no cpu hammering. 

`const Chart = require('gdax-candles');

const eth1s = new Chart({ product: 'ETH-USD', timeframe: '1s' }).start();
const eth2s = new Chart({ product: 'ETH-USD', timeframe: '2s' }).start();
const btc1s = new Chart({ product: 'BTC-USD', timeframe: '1s' }).start();
const btc2s = new Chart({ product: 'BTC-USD', timeframe: '2s' }).start();
const ltc1s = new Chart({ product: 'LTC-USD', timeframe: '1s' }).start();
const ltc2s = new Chart({ product: 'LTC-USD', timeframe: '2s' }).start();
const bch1s = new Chart({ product: 'BCH-USD', timeframe: '1s' }).start();
const bch2s = new Chart({ product: 'BCH-USD', timeframe: '2s' }).start();

eth1s.on('close', candle => console.log('----------- ETH 1s -----------\n', candle));
eth2s.on('close', candle => console.log('----------- ETH 2s -----------\n', candle));
btc1s.on('close', candle => console.log('----------- BTC 1s -----------\n', candle));
btc2s.on('close', candle => console.log('----------- BTC 2s -----------\n', candle));
ltc1s.on('close', candle => console.log('----------- LTC 1s -----------\n', candle));
ltc2s.on('close', candle => console.log('----------- LTC 2s -----------\n', candle));
bch1s.on('close', candle => console.log('----------- BCH 1s -----------\n', candle));
bch2s.on('close', candle => console.log('----------- BCH 2s -----------\n', candle));`

**Comment by slidenerd** [comment]
Never done a PR before :) so gotta find how to do that
A direct improvement over this would be to use the ceil time to get next times.
```

const timeframeToSec = (timeframe) => {

    let time = '';
    let unit;
    const tfsplit = timeframe.split('');
    for (var i in tfsplit) {
        if (!isNaN(tfsplit[i])) {
            time += tfsplit[i];
        } else {
            unit = tfsplit[i];
            break;
        }

    }
    
    return unit && units[unit] && time.length > 0 ? Number(time) * units[unit] : units.s;
}

const timeLeft = (epoch, interval) => {
    console.log("vow",interval, epoch, 60 - Math.floor(epoch / 1000) % 60)
    return interval - (Math.floor(epoch / 1000) % interval);
}

const nextTime = (epoch, interval) => {
    return (Math.floor(epoch / 1000) + timeLeft(epoch, interval)) * 1000;
}

let yourMethod = (nextTime(Date.now(), timeframeToSec('1m')))
let myMethod = Math.ceil(Date.now()/60000) * 60000
console.log(Date.now(), yourMethod, myMethod)
```

Also your chart class currently represents a chart per coin, a slightly more useful addition would be charts that represents multiple charts of multiple coins at the same time

**Comment by slidenerd** [comment]
Apologies that would be a bad idea lol, your clock when it reaches 0 takes the end of the next second, mine doesnt resulting in a double event :)
